const { Double } = require("bson");
const mongoose = require("mongoose");

const proposalDetail = new mongoose.Schema(
  [
    {
      masterPolicy: { type: String },
      masterPolicyNumber: { type: String },
      masterPolicyHolderName: { type: String },
      masterPolicyStartDt: { type: Date },
      masterPolicyEndDt: { type: Date },
      groupCategory: { type: String },
      proposalNo: { type: String },
      proposalStatus: { type: String },
      policyStatus: { type: String },
      policyType: { type: String },
      wattsPolNo: { type: String },
      policyNo: { type: String },
      certificateTyp: { type: String },
      certificateNo: { type: String },
      officeCode: { type: String },
      priorityCustomer: { type: String },
      insuredId: { type: String },
      insuredName: { type: String },
      txtAddressLine1: { type: String },
      insuredMail: { type: String },
      insuredDob: { type: String },
      insuredGender: { type: String },
      majorLineCd: { type: String },
      cardType: { type: String },
      cardInsurer: { type: String },
      periodOfInsurance: { type: String },
      productName: { type: String },
      currencyType: { type: String },
      minorLine: { type: String },
      policyIssuingDt: { type: String },
      cardCategory: { type: String },
      customerAddressLine1: { type: String },
      customerAddressLine2: { type: String },
      customerAddressLine3: { type: String },
      customerArea: { type: String },
      customerLandmark: { type: String },
      customerCountry: { type: String },
      customerState: { type: String },
      customerDistrict: { type: String },
      customerCityTehshiTaluka: { type: String },
      customerPincodePostOffice: { type: String },
      customerPrimaryPhone: { type: Number },
      customerAlternatePhone: { type: Number },
      customerMobile: { type: Number },
      customerEmail: { type: String },
      bankName: { type: String },
      bankBranchName: { type: String },
      bankACNo: { type: String },
      nameAsInBankAccount: { type: String },
      micrCode: { type: String },
      ifscCode: { type: String },
      tpaName: { type: String },
      tpaCode: { type: String },
    },
  ],
  { timestamps: true }
);

module.exports = mongoose.model("proposalDetails", proposalDetail);
